### ISSUE TITLE
Change to page '/design/index' 

### ISSUE THREAD

**Issue by JustinFinkelsteinKainos** [nhsbsa/nhsbsa-digital-playbook#166]
## What
A sentence in the Service Design -> Teams doesn't make sense

## Why
Poor grammar/unclear writing

# Original copy:
> Services as end-users would know them transcend delivery or product teams. Service designers work across a program of work to design the interactions and building blocks that make a service.

# Suggested alternative:
> Services as end-users would know that service designers transcend delivery and product teams. These designers work across a program of work to design the interactions and building blocks that make a service.

**Comment by StephenHill-NHSBSA** [comment]
Page no longer exists since Service Design section re-work
