### ISSUE TITLE
Link to the content style guide to be updated

### ISSUE THREAD

**Issue by nhsbsa-dean** [nhsbsa/nhsbsa-digital-playbook#210]
## What
Content Design Principles (link updates)
- Content design guidance
- Our content design style guide
- Our content design A to Z
- Our content design checklist for editors

## Why
> To help make things clear and consistent across all of our service

**Comment by WORTI3** [comment]
What should the new links be? If known. @nhsbsa-dean

**Comment by nhsbsa-dean** [comment]
Content Design Principles

Content design guidance:
https://www.gov.uk/guidance/content-design 

Our content design style guide:
https://nhsbsauk.sharepoint.com.mcas.ms/sites/DigitalContentDesignTeam/SitePages/NHSBSA-digital-style-guide-and-standards.aspx

Our content design A to Z:
https://nhsbsauk.sharepoint.com.mcas.ms/sites/DigitalContentDesignTeam/SitePages/Content-design-A-to-Z.aspx

Our content design checklist for editors:
https://nhsbsauk.sharepoint.com.mcas.ms/sites/DigitalContentDesignTeam/SitePages/Content-checklist-for-editors.aspx

**Comment by StephenHill-NHSBSA** [comment]
I noticed the links are currently included here:

https://nhsbsa.github.io/nhsbsa-digital-playbook/design/content-designer/about-role/#sources

However the `NHSBSA content design style guide` and `NHSBSA content design checklist for editors` require approval to access them.

Is this request to change the 2 links to the above @nhsbsa-dean?

**Comment by nhsbsa-dean** [comment]
Yeah these are the links sent over by content to be updated @StephenHill-NHSBSA
