### ISSUE TITLE
Update all 'Suggest a change to this page' footer links to point to GitHub 'discussions' instead of 'issues' 

### ISSUE THREAD

**Issue by StephenHill-NHSBSA** [nhsbsa/nhsbsa-digital-playbook#222]
## What
Currently each article within the playbook has a link to 'suggest a change to this page' and when the user clicks the link, it opens up a new GitHub 'issue'.

With our planned trial to use GitHub 'discussions' instead, we should look to change this to point there so that this same functionality can exist.

## Why
To give all interested collaborators the easiest chance to keep suggesting changes and improvements to the DDaT Playbook

## Anything else

![image](https://github.com/nhsbsa/nhsbsa-digital-playbook/assets/45825845/d197ef3b-db9c-45e0-adb0-b40df1459426)

![image](https://github.com/nhsbsa/nhsbsa-digital-playbook/assets/45825845/6690218b-1f7b-4447-b1fb-e24a22e69104)

**Comment by StephenHill-NHSBSA** [comment]
Logged off the back of the DDaT Playbook working group (21/9/2023)

(FYI @yantantether, @nhsbsa-Will, @WORTI3, @nhsbsa-dean)

**Comment by WORTI3** [comment]
Do you need any help with this @StephenHill-NHSBSA ?

**Comment by StephenHill-NHSBSA** [comment]
> Do you need any help with this @StephenHill-NHSBSA ?

Yes please @WORTI3. I'll push the code that I currently have and tag you in it. 

It's been a week or two since I last looked at it, but I couldn't seem to get it to point to the right 'category' etc...
