### ISSUE TITLE
Add note taking 'guidance' to the User Research section

### ISSUE THREAD

**Issue by nhsbsa-dean** [nhsbsa/nhsbsa-digital-playbook#229]
### Discussed in https://github.com/nhsbsa/nhsbsa-digital-playbook/discussions/217

<div type='discussions-op-text'>

<sup>Originally posted by **StephenHill-NHSBSA** September 14, 2023</sup>
## What

To help standardise the way we take notes in our user research sessions across the NHSBSA, we propose to create a number of best practice 'templates' for each User Researcher to use (see https://github.com/nhsbsa/nhsbsa-digital-playbook/discussions/216).

To ensure that the notes are as helpful as possible, we propose to create some 'guidance' for the note taker to follow.

## Why

Currently each User Researcher does things differently. This makes it difficult for each note taker to understand what is expected of them when they move between different projects / services.

Creating some clear 'guidance' on what is expected will help ensure that each User Researcher gets what they need.

</div>

**Comment by lmilor** [comment]
The guidance has been tested and was well received by those who read and engaged with it - happy for this to be pushed to the playbook once Ben has looked over it
