### ISSUE TITLE
Add Delivery Manager content into DDaT Playbook

### ISSUE THREAD

**Issue by StephenHill-NHSBSA** [nhsbsa/nhsbsa-digital-playbook#263]
## What
The Delivery Manager community have extracted information from their old playbook and the following pages are ready to be published:

[The Role of a Delivery Manager](https://github.com/nhsbsa/nhsbsa-digital-playbook/discussions/258)
[Delivery Team](https://github.com/nhsbsa/nhsbsa-digital-playbook/discussions/260)
[Agile Delivery and the Agile Lifecycle](https://github.com/nhsbsa/nhsbsa-digital-playbook/discussions/259)
[Financial Practices](https://github.com/nhsbsa/nhsbsa-digital-playbook/discussions/262)

Further content will be added over time

## Why
Currently the Delivery Manager community don't have a section within the DDaT Playbook, intead their playbook in Word document format - this work is to begin moving that content out.

**Comment by StephenHill-NHSBSA** [comment]
**Home Page:**

![image](https://github.com/nhsbsa/nhsbsa-digital-playbook/assets/45825845/93be9272-d6fd-4ebc-a7d5-d9e08022d717)

**'Delivery Management' page:**

![image](https://github.com/nhsbsa/nhsbsa-digital-playbook/assets/45825845/92f267f4-ece3-41e4-8787-7dab072378ff)

**'About Delivery Management' page:**

![image](https://github.com/nhsbsa/nhsbsa-digital-playbook/assets/45825845/42a79497-23ab-4d81-80d7-5a5f8f0ccc05)

**'Delivery Team' page:**

![image](https://github.com/nhsbsa/nhsbsa-digital-playbook/assets/45825845/04b7f0ba-c6f6-4817-9579-76d7d8a49251)

**'Agile Delivery and Lifecycle' page:**

![image](https://github.com/nhsbsa/nhsbsa-digital-playbook/assets/45825845/c7fa98dc-4d3c-4355-85dd-92af014e0784)

**'Fiancial Practices' page:**

![image](https://github.com/nhsbsa/nhsbsa-digital-playbook/assets/45825845/9a9c6d26-41e4-47ae-9951-4e686af24ab3)

Any thoughts @torihutchinson?

**Comment by torihutchinson** [comment]
@StephenHill-NHSBSA  it is so great to see this come to life, thank you! Few **really** minor things:
- 'About delivery management' page - on Lead DM bit it says 'an sub portfolio' and should say 'a sub portfolio'
- On 'agile and delivery lifecycle' - on the prioritisation and estimation titles, can I change those to read 'Prioritisation Techniques' and 'Estimation Techniques' please? (where it starts going into MOSCOW etc)
- On 'financial practices' page - can I add to the sentence about all delivery colleagues reading the budget guide, that they must 'read and apply'? 
Thanks!
